# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0004_auto_20161202_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='value',
            field=models.IntegerField(blank=True, choices=[(1, 'like'), (-1, 'dislike')], null=True),
        ),
    ]
