# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0005_auto_20161210_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isTrue',
            field=models.BooleanField(default=False),
        ),
    ]
