# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0006_answer_istrue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
